[portal-create]
description = 'Creates a link to a directory so that it can be easily accessed from the command line'
dir = "{{cwd}}"
usage = """
flag "-d --directory [directory]" help="Path of the directory to link (defaults to current directory)"
arg "[linkName]" help="The name of the link (defaults to the name of the directory)"
"""
run = "node $MISE_TASK_DIR/create/create.js"

[portal-delete]
description = 'Removes a previously created link'
dir = "{{cwd}}"
usage = """
arg "<linkNames>" var=#true help="The name of the links to remove (on windows you can omit '.lnk' extension)"
complete "linkNames" run="mise run portal-delete-completion"
"""
run = "node $MISE_TASK_DIR/delete/delete.js"

[portal-delete-completion]
dir = "{{cwd}}"
hide = true
quiet = true
usage = """
arg "[linkNames]" var=#true help="The name of the links to remove (on windows you can omit '.lnk' extension)"
"""
run = "node $MISE_TASK_DIR/delete/delete-completion.js"

[portal-rename]
description = 'Renames a portal link'
dir = "{{cwd}}"
usage = """
arg "<linkName>" help="The name of the portal link to rename"
complete "linkName" run="mise run portal-rename-completion"
arg "<newLinkName>" help="The new name of the portal link"
"""
run = "node $MISE_TASK_DIR/rename/rename.js"

[portal-rename-completion]
dir = "{{cwd}}"
hide = true
quiet = true
run = "node $MISE_TASK_DIR/rename/rename-completion.js"

[portal-target]
description = 'Gets the target of a portal link'
dir = "{{cwd}}"
usage = """
arg "<linkName>" help="The name of the portal link"
complete "linkName" run="mise run portal-target-completion"
"""
run = "node $MISE_TASK_DIR/target/target.js"

[portal-target-completion]
dir = "{{cwd}}"
hide = true
quiet = true
run = "node $MISE_TASK_DIR/target/target-completion.js"
